# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/prian/workspace/pyMidiMap/src/gui/forms/MidiMapDialog.ui'
#
# Created: Wed Jun 29 16:27:27 2011
#      by: PyQt4 UI code generator 4.8.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MidiMapDialog(object):
    def setupUi(self, MidiMapDialog):
        MidiMapDialog.setObjectName(_fromUtf8("MidiMapDialog"))
        MidiMapDialog.resize(487, 270)
        self.verticalLayout = QtGui.QVBoxLayout(MidiMapDialog)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.mapperTabBox = QtGui.QTabWidget(MidiMapDialog)
        self.mapperTabBox.setObjectName(_fromUtf8("mapperTabBox"))
        self.MidiInputTab = QtGui.QWidget()
        self.MidiInputTab.setObjectName(_fromUtf8("MidiInputTab"))
        self.gridLayout = QtGui.QGridLayout(self.MidiInputTab)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label = QtGui.QLabel(self.MidiInputTab)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.inChannelEdit = QtGui.QLineEdit(self.MidiInputTab)
        self.inChannelEdit.setObjectName(_fromUtf8("inChannelEdit"))
        self.gridLayout.addWidget(self.inChannelEdit, 0, 1, 1, 1)
        self.label_2 = QtGui.QLabel(self.MidiInputTab)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.label_3 = QtGui.QLabel(self.MidiInputTab)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 4, 0, 1, 1)
        self.label_4 = QtGui.QLabel(self.MidiInputTab)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 5, 0, 1, 1)
        self.inStatusEdit = QtGui.QLineEdit(self.MidiInputTab)
        self.inStatusEdit.setObjectName(_fromUtf8("inStatusEdit"))
        self.gridLayout.addWidget(self.inStatusEdit, 2, 1, 1, 1)
        self.inData1Edit = QtGui.QLineEdit(self.MidiInputTab)
        self.inData1Edit.setObjectName(_fromUtf8("inData1Edit"))
        self.gridLayout.addWidget(self.inData1Edit, 4, 1, 1, 1)
        self.inData2Edit = QtGui.QLineEdit(self.MidiInputTab)
        self.inData2Edit.setObjectName(_fromUtf8("inData2Edit"))
        self.gridLayout.addWidget(self.inData2Edit, 5, 1, 1, 1)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 2, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 7, 1, 1, 1)
        self.midiCaptureCheckBox = QtGui.QCheckBox(self.MidiInputTab)
        self.midiCaptureCheckBox.setObjectName(_fromUtf8("midiCaptureCheckBox"))
        self.gridLayout.addWidget(self.midiCaptureCheckBox, 6, 1, 1, 1)
        self.mapperTabBox.addTab(self.MidiInputTab, _fromUtf8(""))
        self.ActionTab = QtGui.QWidget()
        self.ActionTab.setObjectName(_fromUtf8("ActionTab"))
        self.layoutWidget = QtGui.QWidget(self.ActionTab)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 451, 264))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.formLayout = QtGui.QFormLayout(self.layoutWidget)
        self.formLayout.setMargin(0)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.outMidiRadioButton = QtGui.QRadioButton(self.layoutWidget)
        self.outMidiRadioButton.setChecked(True)
        self.outMidiRadioButton.setObjectName(_fromUtf8("outMidiRadioButton"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.outMidiRadioButton)
        self.frame = QtGui.QFrame(self.layoutWidget)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.gridLayout_2 = QtGui.QGridLayout(self.frame)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label_8 = QtGui.QLabel(self.frame)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_2.addWidget(self.label_8, 0, 0, 1, 1)
        self.outChannelEdit = QtGui.QLineEdit(self.frame)
        self.outChannelEdit.setObjectName(_fromUtf8("outChannelEdit"))
        self.gridLayout_2.addWidget(self.outChannelEdit, 0, 1, 1, 1)
        self.label_7 = QtGui.QLabel(self.frame)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_2.addWidget(self.label_7, 1, 0, 1, 1)
        self.outStatusEdit = QtGui.QLineEdit(self.frame)
        self.outStatusEdit.setObjectName(_fromUtf8("outStatusEdit"))
        self.gridLayout_2.addWidget(self.outStatusEdit, 1, 1, 1, 1)
        self.label_5 = QtGui.QLabel(self.frame)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_2.addWidget(self.label_5, 2, 0, 1, 1)
        self.outData1Edit = QtGui.QLineEdit(self.frame)
        self.outData1Edit.setObjectName(_fromUtf8("outData1Edit"))
        self.gridLayout_2.addWidget(self.outData1Edit, 2, 1, 1, 1)
        self.label_6 = QtGui.QLabel(self.frame)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_2.addWidget(self.label_6, 3, 0, 1, 1)
        self.outData2Edit = QtGui.QLineEdit(self.frame)
        self.outData2Edit.setObjectName(_fromUtf8("outData2Edit"))
        self.gridLayout_2.addWidget(self.outData2Edit, 3, 1, 1, 1)
        self.outChannelCombo = QtGui.QComboBox(self.frame)
        self.outChannelCombo.setObjectName(_fromUtf8("outChannelCombo"))
        self.outChannelCombo.addItem(_fromUtf8(""))
        self.outChannelCombo.addItem(_fromUtf8(""))
        self.gridLayout_2.addWidget(self.outChannelCombo, 0, 2, 1, 1)
        self.outStatusCombo = QtGui.QComboBox(self.frame)
        self.outStatusCombo.setObjectName(_fromUtf8("outStatusCombo"))
        self.outStatusCombo.addItem(_fromUtf8(""))
        self.outStatusCombo.addItem(_fromUtf8(""))
        self.gridLayout_2.addWidget(self.outStatusCombo, 1, 2, 1, 1)
        self.outData1Combo = QtGui.QComboBox(self.frame)
        self.outData1Combo.setObjectName(_fromUtf8("outData1Combo"))
        self.outData1Combo.addItem(_fromUtf8(""))
        self.outData1Combo.addItem(_fromUtf8(""))
        self.gridLayout_2.addWidget(self.outData1Combo, 2, 2, 1, 1)
        self.outData2Combo = QtGui.QComboBox(self.frame)
        self.outData2Combo.setObjectName(_fromUtf8("outData2Combo"))
        self.outData2Combo.addItem(_fromUtf8(""))
        self.outData2Combo.addItem(_fromUtf8(""))
        self.gridLayout_2.addWidget(self.outData2Combo, 3, 2, 1, 1)
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.frame)
        self.ouKeyRadioButton = QtGui.QRadioButton(self.layoutWidget)
        self.ouKeyRadioButton.setObjectName(_fromUtf8("ouKeyRadioButton"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.ouKeyRadioButton)
        self.outKeyEdit = QtGui.QLineEdit(self.layoutWidget)
        self.outKeyEdit.setEnabled(False)
        self.outKeyEdit.setObjectName(_fromUtf8("outKeyEdit"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.outKeyEdit)
        self.mapperTabBox.addTab(self.ActionTab, _fromUtf8(""))
        self.verticalLayout.addWidget(self.mapperTabBox)
        self.buttonBox = QtGui.QDialogButtonBox(MidiMapDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(MidiMapDialog)
        self.mapperTabBox.setCurrentIndex(0)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), MidiMapDialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), MidiMapDialog.reject)
        QtCore.QObject.connect(self.midiCaptureCheckBox, QtCore.SIGNAL(_fromUtf8("clicked()")), MidiMapDialog.midiCaptureClicked)
        QtCore.QObject.connect(self.ouKeyRadioButton, QtCore.SIGNAL(_fromUtf8("clicked()")), MidiMapDialog.keySequenceClicked)
        QtCore.QObject.connect(self.outMidiRadioButton, QtCore.SIGNAL(_fromUtf8("clicked()")), MidiMapDialog.midiMessageClicked)
        QtCore.QMetaObject.connectSlotsByName(MidiMapDialog)

    def retranslateUi(self, MidiMapDialog):
        MidiMapDialog.setWindowTitle(QtGui.QApplication.translate("MidiMapDialog", "Dialog", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MidiMapDialog", "Channel", None, QtGui.QApplication.UnicodeUTF8))
        self.inChannelEdit.setText(QtGui.QApplication.translate("MidiMapDialog", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MidiMapDialog", "Status", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MidiMapDialog", "Data 1", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MidiMapDialog", "Data 2", None, QtGui.QApplication.UnicodeUTF8))
        self.inStatusEdit.setText(QtGui.QApplication.translate("MidiMapDialog", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.inData1Edit.setText(QtGui.QApplication.translate("MidiMapDialog", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.inData2Edit.setText(QtGui.QApplication.translate("MidiMapDialog", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.midiCaptureCheckBox.setText(QtGui.QApplication.translate("MidiMapDialog", "Midi Capture", None, QtGui.QApplication.UnicodeUTF8))
        self.mapperTabBox.setTabText(self.mapperTabBox.indexOf(self.MidiInputTab), QtGui.QApplication.translate("MidiMapDialog", "Midi Input", None, QtGui.QApplication.UnicodeUTF8))
        self.outMidiRadioButton.setText(QtGui.QApplication.translate("MidiMapDialog", "Midi Message", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("MidiMapDialog", "Channel", None, QtGui.QApplication.UnicodeUTF8))
        self.outChannelEdit.setText(QtGui.QApplication.translate("MidiMapDialog", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("MidiMapDialog", "Status", None, QtGui.QApplication.UnicodeUTF8))
        self.outStatusEdit.setText(QtGui.QApplication.translate("MidiMapDialog", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MidiMapDialog", "Data 1", None, QtGui.QApplication.UnicodeUTF8))
        self.outData1Edit.setText(QtGui.QApplication.translate("MidiMapDialog", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("MidiMapDialog", "Data 2", None, QtGui.QApplication.UnicodeUTF8))
        self.outData2Edit.setText(QtGui.QApplication.translate("MidiMapDialog", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.outChannelCombo.setItemText(0, QtGui.QApplication.translate("MidiMapDialog", "Add", None, QtGui.QApplication.UnicodeUTF8))
        self.outChannelCombo.setItemText(1, QtGui.QApplication.translate("MidiMapDialog", "Assign", None, QtGui.QApplication.UnicodeUTF8))
        self.outStatusCombo.setItemText(0, QtGui.QApplication.translate("MidiMapDialog", "Add", None, QtGui.QApplication.UnicodeUTF8))
        self.outStatusCombo.setItemText(1, QtGui.QApplication.translate("MidiMapDialog", "Assign", None, QtGui.QApplication.UnicodeUTF8))
        self.outData1Combo.setItemText(0, QtGui.QApplication.translate("MidiMapDialog", "Add", None, QtGui.QApplication.UnicodeUTF8))
        self.outData1Combo.setItemText(1, QtGui.QApplication.translate("MidiMapDialog", "Assign", None, QtGui.QApplication.UnicodeUTF8))
        self.outData2Combo.setItemText(0, QtGui.QApplication.translate("MidiMapDialog", "Add", None, QtGui.QApplication.UnicodeUTF8))
        self.outData2Combo.setItemText(1, QtGui.QApplication.translate("MidiMapDialog", "Assign", None, QtGui.QApplication.UnicodeUTF8))
        self.ouKeyRadioButton.setText(QtGui.QApplication.translate("MidiMapDialog", "Key Sequence", None, QtGui.QApplication.UnicodeUTF8))
        self.mapperTabBox.setTabText(self.mapperTabBox.indexOf(self.ActionTab), QtGui.QApplication.translate("MidiMapDialog", "Action", None, QtGui.QApplication.UnicodeUTF8))

